lang: en
engine: knitr
project:
  type: website
  output-dir: docs
  resources: resources

execute:
  freeze: auto

# "R&R ORiRA"
website:
  title: "Recognising and rewarding open research"
  site-url: https://UKRN.github.io/OR4-demo
  repo-url: https://github.com/UKRN/OR4-demo
  image: images/logo.png
  favicon: images/favicon.ico
  bread-crumbs: false
  navbar:
    logo: /images/logos/logo.png
    logo-alt: "Globe with UKRN and big pink UK"
    toggle-position: "right"
    right:
      - text: "About"
        href: about.qmd
      - text: "Overview"
        href: overview.qmd
      - text: "Maturity framework"
        href: maturity-framework.qmd
      - text: "Implementation guide"
        href: guide-contents.qmd
      - text: "Glossary"
        href: glossary.qmd
  sidebar:
    - title: "Implementation guide"
      style: "docked"
      contents:
        - section: Implementation guide
          contents:
          - guide-contents.qmd
          - guide-intro.qmd
          - guide-01.qmd
          - guide-02.qmd
          - guide-03.qmd
          - guide-04.qmd
          - guide-05.qmd
          - guide-06.qmd
          - guide-07.qmd
          - guide-08.qmd
          - guide-09.qmd
        - section: Resources
          contents:
          - text: "Maturity framework PDF"
            href: resources/or4-maturityframework.pdf
    - title: "Maturity framework"
      contents: 
      - maturity-framework.qmd
      - self-assessment.qmd
               
  page-footer:
    background: primary
    left: "![](images/cc-by.svg) ©2024 University of Bristol "
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/UKRN/OR4-demo

format:
  html:
    theme: [simplex, www/style.scss]
    mainfont: Roboto
