lang: en
engine: knitr
project:
  type: website
  output-dir: docs
  resources: resources

execute:
  freeze: auto

website:
  title: "Recognising and Rewarding Open Research Toolkit"
  site-url: https://UKRN.github.io/OR4-demo
  repo-url: https://github.com/UKRN/OR4-demo
  image: images/logo.png
  favicon: images/favicon.ico
  # google-analytics:
  #   tracking-id: "UA-XXXXXXXXX"
  #   storage: cookies
  #   anonymize-ip: true
  navbar:
    logo: /images/logos/logo.png
    logo-alt: "Globe with UKRN and big green UK"
    toggle-position: "right"
    right:
      - text: "About OR4"
        href: about.qmd
      - text: "Overview"
        href: overview.qmd
      - text: "Maturity framework"
        href: maturity-framework.qmd
      - text: "Implementation guide"
        href: guide-contents.qmd
      - text: "Glossary"
        href: glossary.qmd
  sidebar:
    - title: "Implementation guide"
      style: "docked"
      contents:
        - section: Implementation guide
          contents:
          - guide-contents.qmd
          - guide-summary.qmd
          - guide-intro.qmd
          - guide-01.qmd
          - guide-02.qmd
          - guide-03.qmd
          - guide-04.qmd
          - guide-05.qmd
          - section: "Case study"
            contents:
            - case-study-bristol.qmd
          - guide-06.qmd
          - guide-07.qmd
          - guide-08.qmd
          - guide-09.qmd
    - title: "Maturity framework"
      contents:
      - maturity-framework.qmd
      - self-assessment.qmd

  page-footer:
    background: primary
    left: "© 2024 University of Bristol [![](images/cc-by.svg)](https://creativecommons.org/licenses/by/4.0/legalcode.en)"
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/UKRN/OR4-demo

format:
  html:
    theme: [simplex, www/style.scss]
    mainfont: Roboto
