project:
  output-dir: guide
  type: book

book:
  title: |
      ![](images/logos/logo.png){height='100px'}
      Recognising and rewarding open research:
      implementation guide
  author: "© 2024 University of Bristol. Licensed \\href{https://creativecommons.org/licenses/by/4.0/}{CC-BY} "
  site-url: https://recognition.ukrn-openresearch.ac.uk
  license: "© 2024 University of Bristol. Licensed CC-BY"
  chapters:
  - index.md
  - guide-summary.qmd
  - guide-intro.qmd
  - guide-01-commitment.qmd
  - guide-02-leadership.qmd
  - guide-03-strategy.qmd
  - guide-04-communication.qmd
  - guide-05-policy.qmd
  - guide-06-support.qmd
  - guide-07-training.qmd
  - guide-08-monitoring.qmd
  - guide-09-planning.qmd
  - glossary.qmd

format:
  pdf:
    toc: true
    keep-tex: false
    number-sections: false
    colorlinks: true
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 30mm
    margin-bottom: 30mm
    mainfont: Roboto
    sansfont: Roboto
    output-file: "or4-guide"
    output-ext:  "pdf"
    include-in-header:
    - text: |
        \usepackage{fancyhdr}

        \fancyhf{}
        \fancyhead[R]{\href{https://recognition.ukrn-openresearch.ac.uk/}{Recognising and rewarding open research}}
        \cfoot{\thepage}
        \renewcommand\headrulewidth{0pt}
        \pagestyle{fancy}

