project:
  output-dir: resources

book:
  chapters:
  - guide-contents.qmd
  - guide-summary.qmd
  - guide-intro.qmd
  - guide-01-commitment.qmd
  - guide-02-leadership.qmd
  - guide-03-strategy.qmd
  - guide-04-communication.qmd
  - guide-05-policy.qmd
  - guide-06-support.qmd
  - guide-07-training.qmd
  - guide-08-monitoring.qmd
  - guide-09-planning.qmd
  - glossary.qmd

format:
  pdf:
    documentclass: article
    toc: false
    number-sections: false
    colorlinks: true
    include-in-header: pdf-header.tex
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 30mm
    margin-bottom: 30mm
    mainfont: Roboto
