project:
  output-dir: resources

format:
  pdf:
    documentclass: article
    toc: false
    number-sections: false
    colorlinks: true
    include-in-header: pdf-header.tex
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 30mm
    margin-bottom: 30mm
#    mainfont: Roboto
