name: Render PDFs
# manual trigger
on:
  workflow_dispatch:

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        # - name: Install Google Fonts
        #   run: |
        #     wget -O Roboto.zip https://fonts.google.com/download?family=Roboto
        #     unzip -d roboto/ Roboto.zip
        #     mv roboto /usr/share/fonts/
        #     fc-cache -fv

        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.5.57
            tinytex: true

        - name: Set up R
          uses: r-lib/actions/setup-r@v2

        - name: Install packages
          uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages: any::quarto

        - name: Run PDF script
          run: Rscript -e 'source("R/pdf.R")'
          with:
            target: master
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # - name: Render individual PDFs
        #   uses: quarto-dev/quarto-actions/render@v2
        #   with:
        #     to: pdf
        #   env:
        #     QUARTO_PROFILE: guide
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #
        # - name: Rename guide->index
        #   run: mv guide/index.md index.md
        #
        # - name: Render Guide PDF
        #   uses: quarto-dev/quarto-actions/render@v2
        #   with:
        #     to: pdf
        #   env:
        #     QUARTO_PROFILE: guidebook
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #
        # - name: Rename index->guide
        #   run: mv index.md guide/index.md
