name: Render PDFs
# manual trigger
on:
  workflow_dispatch:

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Install Google Fonts
          run: |
            wget -O Roboto.zip https://fonts.google.com/download?family=Roboto
            unzip -d roboto/ Roboto.zip
            mv roboto /usr/share/fonts/
            fc-cache -fv

        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.5.57
            tinytex: true

        - name: Render individual PDFs
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: pdf
          env:
            QUARTO_PROFILE: guide
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Render Guide PDF
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: pdf
          env:
            QUARTO_PROFILE: pages
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
